import {StyleSheet, Text, View} from 'react-native';
import {
  font_black,
  font_secondary,
  primary,
  secondary,
  secondary_light,
  white,
} from '../../Utils/colors';
import {bold, medium, regular} from '../../Utils/fontFamily';
import {font3, font4, font5, font6, font7} from '../../Utils/fontSize';
export default StyleSheet.create({
  main: {backgroundColor: white, padding: 20},
  box: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0.5,
    flex: 0.45,
    borderColor: font_secondary,
  },
  boxheading: {fontSize: font6, color: font_black, fontFamily: bold},
  boxdesc: {fontSize: font4, color: font_secondary, fontFamily: medium},
  boxMain: {
    flexDirection: 'row',
    flex: 1,
    marginTop: 20,
    justifyContent: 'space-between',
  },
  line: {
    borderWidth: 1,
    opacity: 0.2,
    borderColor: font_secondary,
  },
  listRightView: {
    flexDirection: 'row',
    flex: 0.2,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  listTxt: {fontFamily: medium, fontSize: font4, color: font_black},
  img: {width: 15, height: 15},
  listMain: {paddingVertical: 20, flexDirection: 'row', flex: 0},
  hanteraHeaderMain: {
    flex: 0.3,
    justifyContent: 'center',
    backgroundColor: secondary,
  },
  hanteraHeaderSubMain: {
    flexDirection: 'row',
    padding: 20,
    alignItems: 'center',
  },
  hanteraHeaderTxt: {
    fontFamily: medium,
    fontSize: font4,
    color: font_black,
    textAlign: 'center',
  },
  hanteraRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    alignItems: 'center',
  },
  hanteraTitle: {fontSize: font5, fontFamily: bold, color: font_black},
  hanteraDesc: {fontSize: font4, fontFamily: medium, color: font_black},
  bevakningDesc: {fontSize: font3, fontFamily: medium, color: font_black},
  kupongerCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: primary,
    elevation: 1,
    shadowOpacity: 0.05,
    alignItems: 'center',
    justifyContent: 'center',
    // marginRight: 15,
  },
  circleTxt: {fontSize: font4, color: font_black, fontFamily: regular},
  circleViewTxt: {fontSize: font5, color: font_black, fontFamily: regular},
  formanerBannerCircle: {
    backgroundColor: white,
    alignSelf: 'flex-start',
    borderRadius: 50,
    padding: 5,
    shadowOpacity: 0.05,
    marginTop: -45,
  },
  circleImg: {width: 70, height: 70},
  formanerTitle: {fontFamily: regular, color: font_black, fontSize: font5},
  bevakningTitle: {fontFamily: regular, color: font_black, fontSize: font5},
  bevakningDesc: {fontFamily: regular, color: font_black, fontSize: font4},
  tickCircle: {
    width: 22,
    height: 22,
    borderRadius: 15,
    backgroundColor: font_black,
    justifyContent: 'center',
    alignItems: 'center',
  },
  offertaltickCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: font_black,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  offerterTxt: {
    fontSize: font3,
    fontFamily: regular,
    color: font_black,
    marginRight: 5,
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: white,
    paddingHorizontal: 10,
    // margin: 10,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  tabBardateil: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: white,
    padding: 10,
    margin: 10,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  tabItem: {
    // flex: 1,
    alignItems: 'center',
    // paddingHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 5,
  },

  installingCheckTxt: {fontSize: font5, fontFamily: medium, color: font_black},
  installingCheckRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // padding: 10,
    alignItems: 'center',
  },
  omradenRadioRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: 5,
    alignItems: 'center',
  },
  circle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: white,
    elevation: 1,
    shadowOpacity: 0.05,
    alignItems: 'center',
    justifyContent: 'center',
    // marginRight: 15,
  },
  circleImg: {width: 25, height: 25},
  headerTxt: {
    fontSize: font4,
    marginTop: 5,
    width: 70,
    textAlign: 'center',
  },
});
